### ISSUE TITLE
Searching residual file... hang

### ISSUE THREAD

**Issue by francoism90** [cubanpit/cleanupdate#9]
It hangs on this message, anything I can help to debug?

Thanks.

**Comment by cubanpit** [comment]
If you have a very large home directory on a rotational disk (not SSD) this part can take several minutes, if you verify that after some minutes it continues by itself I can't solve the issue, I suggest you to skip that part.
If after a long waiting time it does not continue, you can download the script and remove comment sign (`#`) from line [1340](https://github.com/cubanpit/cleanupdate/blob/master/cleanupdate#L1340) and [1356](https://github.com/cubanpit/cleanupdate/blob/master/cleanupdate#L1356), with this modification it will print every line before executing it. If you give me the exact line I can look into the problem.

Thanks for your interest in cleanupdate

**Comment by francoism90** [comment]
@cubanpit Will try to comment/uncomment some lines in the script as you mention, and report back. I'll close this issue for now. :)
